In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('titanic_clean.csv')
df.head()

   pclass  age  sibsp  parch  emb__freq_enc  survived
0       1   29      0      0       0.698243         1
1       1   28      1      2       0.698243         1
2       1   28      1      2       0.698243         0
3       1   30      1      2       0.698243         0
4       1   25      1      2       0.698243         0

In [ ]:
df.shape

(1309, 6)

In [4]:
df.dtypes

pclass             int64
age                int64
sibsp              int64
parch              int64
emb__freq_enc    float64
survived           int64
dtype: object

In [5]:
df.isna().sum()

pclass           0
age              0
sibsp            0
parch            0
emb__freq_enc    0
survived         0
dtype: int64

In [10]:
features=df.iloc[:,:-1].columns
features

Index(['pclass', 'age', 'sibsp', 'parch', 'emb__freq_enc'], dtype='str')

In [11]:
target='survived'

In [12]:
len(df)

1309

In [13]:
train=df.sample(int(len(df)*.8))
print(train.shape)
train.head()

(1047, 6)

      pclass  age  sibsp  parch  emb__freq_enc  survived
1151       3   28      0      0       0.698243         0
1127       3   19      0      0       0.698243         0
298        1   31      0      0       0.206264         1
235        1   28      0      0       0.698243         1
663        3   26      0      0       0.698243         0

In [14]:
test=df.drop(index=train.index)
print(test.shape)
test.head()

(262, 6)

    pclass  age  sibsp  parch  emb__freq_enc  survived
8        1   53      2      0       0.698243         1
11       1   18      1      0       0.206264         1
21       1   47      1      1       0.698243         1
24       1   29      0      0       0.698243         1
38       1   41      0      0       0.698243         0

In [15]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(df,test_size=0.2, random_state=42)
print(train.shape)
print(test.shape)

(1047, 6)
(262, 6)

In [16]:
print(train.head())
test.head()

     pclass  age  sibsp  parch  emb__freq_enc  survived
772       3   17      0      0       0.698243         0
543       2   36      0      0       0.698243         0
289       1   18      0      2       0.698243         1
10        1   47      1      0       0.206264         0
147       1   28      0      0       0.698243         0

      pclass  age  sibsp  parch  emb__freq_enc  survived
1148       3   35      0      0       0.698243         0
1049       3   20      1      1       0.206264         1
982        3   28      0      0       0.698243         0
808        3   28      0      0       0.698243         0
1195       3   28      0      0       0.093965         0

In [17]:
train.survived.value_counts()

survived
0    665
1    382
Name: count, dtype: int64

In [18]:
test.survived.value_counts()

survived
0    144
1    118
Name: count, dtype: int64

In [19]:
df.survived.value_counts()

survived
0    809
1    500
Name: count, dtype: int64

In [20]:
382/500

0.764

In [21]:
665/809

0.8220024721878862

In [22]:
train_df,test_df=train_test_split(df,test_size=0.2, random_state=42,stratify=df.survived)

In [23]:
train_df.survived.value_counts()

survived
0    647
1    400
Name: count, dtype: int64

In [24]:
test_df.survived.value_counts()

survived
0    162
1    100
Name: count, dtype: int64

In [25]:
df.survived.value_counts()

survived
0    809
1    500
Name: count, dtype: int64

In [28]:
400/500

0.8

In [26]:
809*.8 #train 80%

647.2

In [27]:
809-647 #test 20%

162

In [29]:
train_df.head()

      pclass  age  sibsp  parch  emb__freq_enc  survived
999        3   28      0      0       0.093965         1
392        2   24      1      0       0.206264         1
628        3   11      4      2       0.698243         0
1165       3   25      0      0       0.206264         0
604        3   16      0      0       0.698243         1

In [30]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_score,KFold
from sklearn.metrics import confusion_matrix, accuracy_score

In [31]:
X_train=train_df[features]
y_train=train_df[target]
X_test=test_df[features]
y_test=test_df[target]

In [37]:
X_test.head()

      pclass  age  sibsp  parch  emb__freq_enc
1028       3   28      1      0       0.093965
1121       3   28      1      1       0.206264
1155       3   28      0      0       0.698243
1251       3   30      0      0       0.698243
721        3   36      0      0       0.698243

In [38]:
svcmodel=SVC(kernel='linear')
CARTModel=DecisionTreeClassifier()

In [39]:
svcmodel.fit(X_train,y_train)

SVC(kernel='linear')

In [40]:
CARTModel.fit(X_train,y_train)
#after fitting train data, model is already a trained ML model

DecisionTreeClassifier()

In [41]:
predicted1=svcmodel.predict(X_test) #SVM
print(len(y_test))
print('Prediction:\n',predicted1)
print('Actual:\n',y_test.values)

262
Prediction:
 [0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 0 0
 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0
 0 1 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 1 0
 0 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 0 1]
Actual:
 [1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0
 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0
 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0
 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1
 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0]

In [42]:
print('\nAlgorithm: Support Vector Machine')
res_cm = confusion_matrix(y_test, predicted1)
print('Confusion Matrix:\n',res_cm)
res_acc = accuracy_score(y_test,predicted1)
print("Accuracy:",res_acc)

Algorithm: Support Vector Machine
Confusion Matrix:
 [[133  29]
 [ 47  53]]
Accuracy: 0.7099236641221374

In [44]:
(133+53)/(133+29+47+53)

0.7099236641221374

In [45]:
predicted2=CARTModel.predict(X_test)
print(len(y_test))
print('Prediction:\n',predicted2)
print('Actual:\n',y_test.values)

262
Prediction:
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0
 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0
 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0
 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0
 1 1 0 1 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0
 0 0 1]
Actual:
 [1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0
 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0
 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0
 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1
 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0]

In [46]:
print('\nAlgorithm: Decision Tree Classifier')
res_cm = confusion_matrix(y_test, predicted2)
print('Confusion Matrix:\n',res_cm)
res_acc = accuracy_score(y_test,predicted2)
print("Accuracy:",res_acc)

Algorithm: Decision Tree Classifier
Confusion Matrix:
 [[132  30]
 [ 59  41]]
Accuracy: 0.6603053435114504

In [47]:
res_cm[0][0] #true negatives

np.int64(132)

In [48]:
res_cm[1][0] #false negatives

np.int64(59)

In [49]:
res_cm[1][1] #true positives

np.int64(41)

In [50]:
res_cm[0][1] #false positive

np.int64(30)

In [51]:
import pickle
pickle.dump(svcmodel,open('model_svc.pkl','wb'))
pickle.dump(CARTModel,open('model_cart.pkl','wb'))

In [56]:
model1=pickle.load(open('model_svc.pkl','rb'))

EOFError: Ran out of input

In [57]:
with open('model_svc.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

print(loaded_data)

EOFError: Ran out of input

In [53]:
X_test.head()

      pclass  age  sibsp  parch  emb__freq_enc
1028       3   28      1      0       0.093965
1121       3   28      1      1       0.206264
1155       3   28      0      0       0.698243
1251       3   30      0      0       0.698243
721        3   36      0      0       0.698243

In [55]:
model1.predict([3,36,0,0,0.698243])

AttributeError: '_io.BufferedWriter' object has no attribute 'predict'